################################################################################
#
# fruitjam-netbox
#
################################################################################

FRUITJAM_NETBOX_VERSION = 1.37.0
FRUITJAM_NETBOX_SOURCE = busybox-$(FRUITJAM_NETBOX_VERSION).tar.bz2
FRUITJAM_NETBOX_SITE = https://busybox.net/downloads
FRUITJAM_NETBOX_LICENSE = GPL-2.0
FRUITJAM_NETBOX_LICENSE_FILES = LICENSE
FRUITJAM_NETBOX_DEPENDENCIES = busybox
FRUITJAM_NETBOX_CFLAGS = $(TARGET_CFLAGS)
FRUITJAM_NETBOX_LDFLAGS = $(TARGET_LDFLAGS)

FRUITJAM_NETBOX_MAKE_ENV = \
	$(TARGET_MAKE_ENV) \
	CFLAGS="$(FRUITJAM_NETBOX_CFLAGS)"

FRUITJAM_NETBOX_MAKE_OPTS = \
	AR="$(TARGET_AR)" \
	NM="$(TARGET_NM)" \
	RANLIB="$(TARGET_RANLIB)" \
	CC="$(TARGET_CC)" \
	ARCH=$(NORMALIZED_ARCH) \
	EXTRA_LDFLAGS="$(FRUITJAM_NETBOX_LDFLAGS)" \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	SKIP_STRIP=y

define FRUITJAM_NETBOX_ENABLE
	$(SED) '/^\(# \)\?$(1)\>/d' $(@D)/.config
	echo '$(1)=y' >> $(@D)/.config
endef

define FRUITJAM_NETBOX_DISABLE
	$(SED) '/^\(# \)\?$(1)\>/d' $(@D)/.config
	echo '# $(1) is not set' >> $(@D)/.config
endef

define FRUITJAM_NETBOX_SET
	$(SED) '/^\(# \)\?$(1)\>/d' $(@D)/.config
	echo '$(1)=$(2)' >> $(@D)/.config
endef

define FRUITJAM_NETBOX_RESET_CONFIG
	$(FRUITJAM_NETBOX_MAKE_ENV) $(MAKE) -C $(@D) \
		$(FRUITJAM_NETBOX_MAKE_OPTS) allnoconfig
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_STATIC)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_NOMMU)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_LFS)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_BUSYBOX)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_PREFER_APPLETS)
endef

define FRUITJAM_NETBOX_FINISH_CONFIG
	yes "" | $(FRUITJAM_NETBOX_MAKE_ENV) $(MAKE) -C $(@D) \
		$(FRUITJAM_NETBOX_MAKE_OPTS) oldconfig
	$(FRUITJAM_NETBOX_MAKE_ENV) $(MAKE) -C $(@D) \
		$(FRUITJAM_NETBOX_MAKE_OPTS) clean
endef

define FRUITJAM_NETBOX_BUILD_ONE
	$(call FRUITJAM_NETBOX_RESET_CONFIG)
	$(FRUITJAM_NETBOX_CONFIG_$(1))
	$(call FRUITJAM_NETBOX_FINISH_CONFIG)
	$(FRUITJAM_NETBOX_MAKE_ENV) $(MAKE) -C $(@D) \
		$(FRUITJAM_NETBOX_MAKE_OPTS) busybox
	cp $(@D)/busybox $(@D)/$(2)
	$(TARGET_CROSS)flthdr -s 4096 $(@D)/$(2)
endef

define FRUITJAM_NETBOX_CONFIG_CAT
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_CAT)
endef

define FRUITJAM_NETBOX_CONFIG_ECHO
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_ECHO)
endef

define FRUITJAM_NETBOX_CONFIG_LS
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_LS)
endef

define FRUITJAM_NETBOX_CONFIG_MKDIR
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_MKDIR)
endef

define FRUITJAM_NETBOX_CONFIG_MOUNT
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_MOUNT)
endef

define FRUITJAM_NETBOX_CONFIG_PRINTF
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_PRINTF)
endef

define FRUITJAM_NETBOX_CONFIG_SLEEP
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_SLEEP)
endef

define FRUITJAM_NETBOX_CONFIG_UMOUNT
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_UMOUNT)
endef

define FRUITJAM_NETBOX_CONFIG_VI
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_VI)
	$(call FRUITJAM_NETBOX_SET,CONFIG_FEATURE_VI_MAX_LEN,2048)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_VI_8BIT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_VI_COLON)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_VI_SEARCH)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_VI_USE_SIGNALS)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_VI_READONLY)
endef

define FRUITJAM_NETBOX_CONFIG_PS
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_PS)
endef

define FRUITJAM_NETBOX_CONFIG_KILLALL
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_KILLALL)
endef

define FRUITJAM_NETBOX_CONFIG_IFCONFIG
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_IFCONFIG)
endef

define FRUITJAM_NETBOX_CONFIG_INITBOX
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_INIT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_USE_INITTAB)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_INIT_SCTTY)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_INIT_QUIET)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_WAIT_FOR_INIT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_SHELL_HUSH)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_SH_IS_HUSH)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_INTERACTIVE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_JOB)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_IF)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_LOOPS)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_CASE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_FUNCTIONS)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_LOCAL)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_EXPORT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_SET)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_UNSET)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_READ)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_TEST)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_WAIT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_TRAP)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_COMMAND)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_ECHO)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_PRINTF)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_SH_MATH)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_SH_MATH_64)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_EDITING)
	$(call FRUITJAM_NETBOX_SET,CONFIG_FEATURE_EDITING_MAX_LEN,512)
	$(call FRUITJAM_NETBOX_SET,CONFIG_FEATURE_EDITING_HISTORY,32)
endef

define FRUITJAM_NETBOX_CONFIG_HUSH
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_SHELL_HUSH)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_INTERACTIVE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_IF)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_LOOPS)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_CASE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_FUNCTIONS)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_EXPORT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_SET)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_UNSET)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_READ)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_TEST)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_WAIT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_COMMAND)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_ECHO)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HUSH_PRINTF)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_SH_MATH)
endef

define FRUITJAM_NETBOX_CONFIG_COREBOX
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_BASENAME)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_CHGRP)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_CHMOD)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_CHOWN)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_CP)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_DATE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_DD)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_DIRNAME)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_DMESG)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_ENV)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FALSE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_GETOPT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HALT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HOSTNAME)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_KILL)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_LN)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_MKNOD)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_MORE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_MV)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_PING)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_POWEROFF)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_PRINTENV)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_PWD)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_REBOOT)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_RM)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_RMDIR)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_STTY)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_SYNC)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TEE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TEST)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TOUCH)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TRUE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_WHICH)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_XARGS)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_YES)
endef

define FRUITJAM_NETBOX_CONFIG_GREP
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_GREP)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_EGREP)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FGREP)
endef

define FRUITJAM_NETBOX_CONFIG_SED
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_SED)
endef

define FRUITJAM_NETBOX_CONFIG_DF
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_DF)
endef

define FRUITJAM_NETBOX_CONFIG_HEAD
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HEAD)
endef

define FRUITJAM_NETBOX_CONFIG_TAIL
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TAIL)
endef

define FRUITJAM_NETBOX_CONFIG_WC
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_WC)
endef

define FRUITJAM_NETBOX_CONFIG_CUT
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_CUT)
endef

define FRUITJAM_NETBOX_CONFIG_TR
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TR)
endef

define FRUITJAM_NETBOX_CONFIG_UNAME
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_UNAME)
endef


define FRUITJAM_NETBOX_CONFIG_NETSTAT
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_NETSTAT)
endef

define FRUITJAM_NETBOX_CONFIG_NC
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_NC)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_NC_SERVER)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_NC_EXTRA)
endef

define FRUITJAM_NETBOX_CONFIG_HTTPD
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_HTTPD)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_HTTPD_CGI)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_HTTPD_CONFIG_WITH_SCRIPT_INTERPR)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_HTTPD_SET_REMOTE_PORT_TO_ENV)
endef

define FRUITJAM_NETBOX_CONFIG_FTPD
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FTPD)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_FTPD_WRITE)
endef

define FRUITJAM_NETBOX_CONFIG_TFTP
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TFTP)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_TFTP_GET)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_TFTP_PUT)
endef

define FRUITJAM_NETBOX_CONFIG_TFTPD
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TFTPD)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_TFTP_GET)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_TFTP_PUT)
endef

define FRUITJAM_NETBOX_CONFIG_SV
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TCPSVD)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_UDPSVD)
endef

define FRUITJAM_NETBOX_CONFIG_TELNETD
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_DEVPTS)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TELNETD)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_TELNETD_STANDALONE)
	$(call FRUITJAM_NETBOX_SET,CONFIG_FEATURE_TELNETD_PORT_DEFAULT,23)
endef

define FRUITJAM_NETBOX_CONFIG_TELNET
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_TELNET)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_TELNET_TTYPE)
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_FEATURE_TELNET_AUTOLOGIN)
endef

define FRUITJAM_NETBOX_CONFIG_WGET
	$(call FRUITJAM_NETBOX_ENABLE,CONFIG_WGET)
endef

define FRUITJAM_NETBOX_BUILD_CMDS
	$(call FRUITJAM_NETBOX_BUILD_ONE,INITBOX,fruitjam-busybox)
	$(call FRUITJAM_NETBOX_BUILD_ONE,HUSH,fruitjam-hush)
	$(call FRUITJAM_NETBOX_BUILD_ONE,COREBOX,fruitjam-corebox)
	$(call FRUITJAM_NETBOX_BUILD_ONE,GREP,fruitjam-grep)
	$(call FRUITJAM_NETBOX_BUILD_ONE,SED,fruitjam-sed)
	$(call FRUITJAM_NETBOX_BUILD_ONE,DF,fruitjam-df)
	$(call FRUITJAM_NETBOX_BUILD_ONE,HEAD,fruitjam-head)
	$(call FRUITJAM_NETBOX_BUILD_ONE,TAIL,fruitjam-tail)
	$(call FRUITJAM_NETBOX_BUILD_ONE,WC,fruitjam-wc)
	$(call FRUITJAM_NETBOX_BUILD_ONE,CUT,fruitjam-cut)
	$(call FRUITJAM_NETBOX_BUILD_ONE,TR,fruitjam-tr)
	$(call FRUITJAM_NETBOX_BUILD_ONE,UNAME,fruitjam-uname)
	$(call FRUITJAM_NETBOX_BUILD_ONE,CAT,fruitjam-cat)
	$(call FRUITJAM_NETBOX_BUILD_ONE,ECHO,fruitjam-echo)
	$(call FRUITJAM_NETBOX_BUILD_ONE,LS,fruitjam-ls)
	$(call FRUITJAM_NETBOX_BUILD_ONE,MKDIR,fruitjam-mkdir)
	$(call FRUITJAM_NETBOX_BUILD_ONE,MOUNT,fruitjam-mount)
	$(call FRUITJAM_NETBOX_BUILD_ONE,PRINTF,fruitjam-printf)
	$(call FRUITJAM_NETBOX_BUILD_ONE,SLEEP,fruitjam-sleep)
	$(call FRUITJAM_NETBOX_BUILD_ONE,UMOUNT,fruitjam-umount)
	$(call FRUITJAM_NETBOX_BUILD_ONE,VI,fruitjam-vi)
	$(call FRUITJAM_NETBOX_BUILD_ONE,PS,fruitjam-ps)
	$(call FRUITJAM_NETBOX_BUILD_ONE,KILLALL,fruitjam-killall)
	$(call FRUITJAM_NETBOX_BUILD_ONE,IFCONFIG,fruitjam-ifconfig)
	$(call FRUITJAM_NETBOX_BUILD_ONE,NETSTAT,fruitjam-netstat)
	$(call FRUITJAM_NETBOX_BUILD_ONE,NC,fruitjam-nc)
	$(call FRUITJAM_NETBOX_BUILD_ONE,HTTPD,fruitjam-httpd)
	$(call FRUITJAM_NETBOX_BUILD_ONE,FTPD,fruitjam-ftpd)
	$(call FRUITJAM_NETBOX_BUILD_ONE,TFTP,fruitjam-tftp)
	$(call FRUITJAM_NETBOX_BUILD_ONE,TFTPD,fruitjam-tftpd)
	$(call FRUITJAM_NETBOX_BUILD_ONE,SV,fruitjam-sv)
	$(call FRUITJAM_NETBOX_BUILD_ONE,TELNETD,fruitjam-telnetd)
	$(call FRUITJAM_NETBOX_BUILD_ONE,TELNET,fruitjam-telnet)
	$(call FRUITJAM_NETBOX_BUILD_ONE,WGET,fruitjam-wget)
endef

define FRUITJAM_NETBOX_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 4755 $(@D)/fruitjam-busybox $(TARGET_DIR)/bin/busybox
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-hush $(TARGET_DIR)/usr/bin/hush
	find $(TARGET_DIR)/bin $(TARGET_DIR)/sbin $(TARGET_DIR)/usr/bin \
		$(TARGET_DIR)/usr/sbin -type l | while read link; do \
		target=$$(readlink "$$link"); \
		case "$$target" in busybox|../bin/busybox|../../bin/busybox) \
			rm -f "$$link";; \
		esac; \
	done
	ln -sf busybox $(TARGET_DIR)/bin/sh
	ln -sf ../usr/bin/hush $(TARGET_DIR)/bin/hush
	ln -sf ../bin/busybox $(TARGET_DIR)/sbin/init
	rm -f $(TARGET_DIR)/bin/netbox \
		$(TARGET_DIR)/bin/cat \
		$(TARGET_DIR)/bin/echo \
		$(TARGET_DIR)/bin/ls \
		$(TARGET_DIR)/bin/mkdir \
		$(TARGET_DIR)/bin/mount \
		$(TARGET_DIR)/usr/bin/printf \
		$(TARGET_DIR)/bin/sleep \
		$(TARGET_DIR)/bin/umount \
		$(TARGET_DIR)/bin/vi \
		$(TARGET_DIR)/bin/ps \
		$(TARGET_DIR)/usr/bin/killall \
		$(TARGET_DIR)/sbin/ifconfig \
		$(TARGET_DIR)/bin/netstat
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-corebox $(TARGET_DIR)/bin/corebox
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-grep $(TARGET_DIR)/bin/grep
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-sed $(TARGET_DIR)/bin/sed
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-df $(TARGET_DIR)/bin/df
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-head $(TARGET_DIR)/usr/bin/head
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-tail $(TARGET_DIR)/usr/bin/tail
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-wc $(TARGET_DIR)/usr/bin/wc
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-cut $(TARGET_DIR)/usr/bin/cut
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-tr $(TARGET_DIR)/usr/bin/tr
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-uname $(TARGET_DIR)/bin/uname
	ln -sf grep $(TARGET_DIR)/bin/egrep
	ln -sf grep $(TARGET_DIR)/bin/fgrep
	for app in chgrp chmod chown cp date dd dmesg false \
		getopt hostname kill ln mknod more mv ping printenv pwd rm \
		rmdir stty sync touch true; do \
		ln -sf corebox $(TARGET_DIR)/bin/$$app; \
	done
	for app in basename dirname env tee test which xargs \
		yes; do \
		ln -sf ../../bin/corebox $(TARGET_DIR)/usr/bin/$$app; \
	done
	for app in halt poweroff reboot; do \
		ln -sf ../bin/corebox $(TARGET_DIR)/sbin/$$app; \
	done
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-cat $(TARGET_DIR)/bin/cat
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-echo $(TARGET_DIR)/bin/echo
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-ls $(TARGET_DIR)/bin/ls
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-mkdir $(TARGET_DIR)/bin/mkdir
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-mount $(TARGET_DIR)/bin/mount
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-printf $(TARGET_DIR)/usr/bin/printf
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-sleep $(TARGET_DIR)/bin/sleep
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-umount $(TARGET_DIR)/bin/umount
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-vi $(TARGET_DIR)/bin/vi
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-ps $(TARGET_DIR)/bin/ps
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-killall $(TARGET_DIR)/usr/bin/killall
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-ifconfig $(TARGET_DIR)/sbin/ifconfig
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-netstat $(TARGET_DIR)/bin/netstat
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-nc $(TARGET_DIR)/usr/bin/nc
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-httpd $(TARGET_DIR)/usr/sbin/httpd
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-ftpd $(TARGET_DIR)/usr/sbin/ftpd
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-tftp $(TARGET_DIR)/usr/bin/tftp
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-tftpd $(TARGET_DIR)/usr/sbin/tftpd
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-sv $(TARGET_DIR)/usr/bin/tcpsvd
		$(INSTALL) -D -m 0755 $(@D)/fruitjam-sv $(TARGET_DIR)/usr/bin/udpsvd
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-telnetd $(TARGET_DIR)/usr/sbin/telnetd
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-telnet $(TARGET_DIR)/usr/bin/telnet
	$(INSTALL) -D -m 0755 $(@D)/fruitjam-wget $(TARGET_DIR)/usr/bin/wget
endef

$(eval $(generic-package))
