
################################################################################
#
# PICO2_BOOTLOADER
#
################################################################################

PICO2_BOOTLOADER_VERSION = 1.0
PICO2_BOOTLOADER_SITE = $(PICO2_BOOTLOADER_PKGDIR)/bootloader
PICO2_BOOTLOADER_SITE_METHOD = local
PICO2_BOOTLOADER_INSTALL_IMAGES = YES
PICO2_BOOTLOADER_INSTALL_TARGET = NO

define PICO2_BOOTLOADER_BUILD_CMDS
	$(MAKE) CROSS_COMPILE="$(TARGET_CROSS)" \
		PICO2_BOOTLOADER_UART_INDEX=$(BR2_PACKAGE_PICO2_BOOTLOADER_UART_INDEX) \
		PICO2_BOOTLOADER_UART_TX_PIN=$(BR2_PACKAGE_PICO2_BOOTLOADER_UART_TX_PIN) \
		PICO2_BOOTLOADER_UART_RX_PIN=$(BR2_PACKAGE_PICO2_BOOTLOADER_UART_RX_PIN) \
		PICO2_BOOTLOADER_PSRAM_CS_PIN=$(BR2_PACKAGE_PICO2_BOOTLOADER_PSRAM_CS_PIN) \
		PICO2_BOOTLOADER_LED_PIN=$(BR2_PACKAGE_PICO2_BOOTLOADER_LED_PIN) \
		PICO2_BOOTLOADER_LED_ACTIVE_LOW=$(if $(BR2_PACKAGE_PICO2_BOOTLOADER_LED_ACTIVE_LOW),1,0) \
		PICO2_BOOTLOADER_RESCUE_WATCHDOG_MS=$(BR2_PACKAGE_PICO2_BOOTLOADER_RESCUE_WATCHDOG_MS) \
		-C $(@D) bootloader.bin
endef

define PICO2_BOOTLOADER_INSTALL_IMAGES_CMDS
	cp $(@D)/bootloader.bin $(BINARIES_DIR)/
endef

$(eval $(generic-package))
